### ISSUE TITLE
Why a fork?

### ISSUE THREAD

**Issue by patrobinson** [vmware/vmware-go-kcl#18]
Hi I'm the original creator of https://github.com/patrobinson/gokini from which this project was forked. I'm wondering why it was forked and the changes not instead integrated upstream? I'm happy to collaborate on this together, I'm glad to see you've implemented dealing with shard splits and merges.

**Comment by taojwmware** [comment]
Thanks for your original contribution on this effort. The code structure are quite different and it also combines with lots of original AWS KCL and Kinesis Connector Library concepts. One major design goal is to make it as close as possible to AWS KCL even using the same constant and parameter names in order to make it easy for cross-referencing on AWS KCL. 
I will be happy to contribute back to shard splitting and merging. But I am not sure whether you'd like to accept other changes such as: the structural change.

**Comment by patrobinson** [comment]
Thanks @taojwmware for the explanation.

I'm most curious in what you've found using this in production environments. I noticed some changes to not die when non-fatal errors occur during shard allocation, [which I've ported](https://github.com/patrobinson/gokini/commit/469ad86ece4048c61346e3ddf94ecde1a2dcfd82) but any other issues you have found would be much appreciated to know about so I can address them.

One thing you're missing from this fork is changes I made to [avoid race conditions](https://github.com/patrobinson/gokini/pull/4/files) when checkpointing.

I intend to keep the structure the same in my library as it keeps the godocs clean and easy to read, particularly with the [examples](https://godoc.org/github.com/patrobinson/gokini#example-RecordConsumer)
