### ISSUE TITLE
Allow passing of AWS session

### ISSUE THREAD

**Issue by Sytten** [vmware/vmware-go-kcl#32]
I think it's generally a good idea to allow people to provide a full AWS session. I have already forked the project to work on that, but I just want to make sure this is ok with your vision of the project.

**Comment by taojwmware** [comment]
The current code has a way to pass in checkpointer and Kinesis already. The session can be managed using the approach.
https://github.com/vmware/vmware-go-kcl/blob/master/clientlibrary/worker/worker.go#L94

Here is the example on how to use it:
https://github.com/vmware/vmware-go-kcl/blob/master/test/worker_custom_test.go#L145

Passing session exposes too much detail. Our long term goal is to make wmware-go-kcl to be a generic streaming platform processing engine instead of solely tight to Kinesis. The next big step is to support Kafka.

**Comment by Sytten** [comment]
Good I will use this approach, I need to use a session because we use local-backend for integration tests (with a custom endpoint).
