### ISSUE TITLE
Support enhanced fan-out

### ISSUE THREAD

**Issue by clocklear** [vmware/vmware-go-kcl#34]
As of March 8th, 2019, the aws-sdk-go package has had (what appears to be) full support for `SubscribeToStream`, which allows for subscribers to have shard records pushed to them instead of having to deal with shard iterators and polling.  This is also necessary for enhanced fan-out, which gives dedicated throughput to consumers and consumer-level metrics inside cloudwatch.

What do you think the level of effort would be to add this functionality to this project?  It would help us out immensely.

Supporting links:
https://github.com/aws/aws-sdk-go/pull/2402
https://docs.aws.amazon.com/streams/latest/dev/introduction-to-enhanced-consumers.html
https://docs.aws.amazon.com/streams/latest/dev/building-enhanced-consumers-api.html

**Comment by taojwmware** [comment]
It is a nice feature to have. I just took a look on AWS KCL and it took them 1 milestone to accomplish it.
https://github.com/awslabs/amazon-kinesis-client/blob/master/CHANGELOG.md

I would take a deeper look on the tradeoff:
"allows for subscribers to have shard records pushed to them instead of having to deal with shard iterators and polling"

From KCL user point of view, it doesn't matter much because all of complexity are handled by KCL. The things remaining are performance, reliability, scalability, cost, etc.
