### ISSUE TITLE
DynamoCheckpoint does not have a way to set "skipTableCheck"

### ISSUE THREAD

**Issue by victorl-splunk** [vmware/vmware-go-kcl#38]
Source: https://github.com/vmware/vmware-go-kcl/blob/master/clientlibrary/checkpoint/dynamodb-checkpointer.go

There is a parameter (skipTableCheck) that allows the DynamoCheckpoint's Init() method to skip the table check. This parameter cannot be set. 

It would be great if we can add a setter to skip the table check so there can be the option for callers to provide their own provisioned DynamoDB table instead of going through the create table workflow and making an extra call to the DynamoDB API.

**Comment by taojwmware** [comment]
The variable is supposed to be used by unit test only. It is originally created by https://github.com/patrobinson/gokini/blob/master/checkpointer_test.go

However, I think it is redundant because the mockDynamoDB has tableExist field already.  On the other hand, the code does check the existence of a table and use it if it does exist. Also, creating a dynamodb table is very cheap operation and it only need to do once during initialization. 

I will remove skipTableCheck to get rid of confusion instead.

**Comment by taojwmware** [comment]
Fixed in https://github.com/vmware/vmware-go-kcl/pull/39
