### ISSUE TITLE
Recording a lot of ProvisionedThroughputExceededException

### ISSUE THREAD

**Issue by dovydas55** [vmware/vmware-go-kcl#46]
Been recording a lot of `Error getting records from shard ProvisionedThroughputExceededException`. Wondering if this is something to do with describing the stream for shard discovery in the event loop? We are using many streams associated with the single AWS account. Wouldnt make more sense to set a single shard id for each consumer?

**Comment by taojwmware** [comment]
Each KCL app only handle one stream with multiple shards. If there are 5 streams, you need to create 5 KCL app and give different app name which will create multiple DynamoDB tables. 

KCL does not have a way to handle individual shard. If you need to directly read from any specific shard, you need to use AWS go-sdk directly instead.

For ProvisionedThroughputExceededException, it is because the KCL reads Kinesis stream too fast which mean there isn't any data in to stream. So, you do need to configure IdleTimeBetweenReadsInMillis to put delay between empty read. 

If you read record each time, you must have very faster processor. Then, you need to make WithMaxRecords a larger number to get more data in a batch. 

If all of them do not work, you need to split shard. Kinesis has fix capacity for one shard. Need to split shard whenever exceeding its capacity.
